~/pset2/readability/ $ make readability
clang -ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow    readability.c  -lcrypt -lcs50 -lm -o readability
~/pset2/readability/ $ ./readability -d "Would you like them here or there? I would not like them here or there. I would not like them anywhere."
stats for nerds:
81 letters 21 words & 3 sentenes
L = 81.00 ÷ 21.00 × 100 = 385.71
S = 3.00 ÷ 21.00 × 100 = 14.29
index = 0.0588 * 385.7143 - 0.296 * 14.2857 - 15.8 = 2.6514 rounded to 3
Grade 3
~/pset2/readability/ $ ./readability -d "In my younger and more vulnerable years my father gave me some advice that I've been turning over in my mind ever since."
stats for nerds:
97 letters 23 words & 1 sentenes
L = 97.00 ÷ 23.00 × 100 = 421.74
S = 1.00 ÷ 23.00 × 100 = 4.35
index = 0.0588 * 421.7391 - 0.296 * 4.3478 - 15.8 = 7.7113 rounded to 8
Grade 8
~/pset2/readability/ $ check50 cs50/problems/2020/x/readability
Connecting......
Authenticating....
GitHub username: scarodj
GitHub password: *********
Verifying.....
Preparing.....
Uploading............
Waiting for results..............................................
Results for cs50/problems/2020/x/readability generated by check50 v3.1.2
:) readability.c exists
:) readability.c compiles
:( handles single sentence with multiple words
    expected "Grade 7\n", not "Grade 8\n"
:) handles punctuation within a single sentence
:) handles more complex single sentence
:) handles multiple sentences
:) handles multiple more complex sentences
:) handles longer passages
:( handles questions in passage
    expected "Grade 2\n", not "Grade 3\n"
:) handles reading level before Grade 1
:) handles reading level at Grade 16+
To see the results in your browser go to https://submit.cs50.io/check50/7ce9efd47f11a1f4d0ed731105593466f0a13001
~/pset2/readability/ $ 
